name: Build Choco With GitHub Actions
run-name: "${{ github.actor }} is building the choco packge ${{ github.ref_name }} :)"
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "!v[0-9]+.[0-9]+.[0-9]+-rc"
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run test.ps1
        run: |
          (Get-Location).Path
          .\test.ps1

      - name: Zip
        run: |
          $compressArgs = @{
            Path = @(
              ".\test.ps1"
            )
            CompressionLevel = "Fastest"
            Destination = ".\choco\tools\test.zip"
          }
          Compress-Archive @compressArgs

      - name: Choco Build
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: pack .\choco\test_choco_github_actions.nuspec --outputdirectory build
      
      - name: Show Artifacts
        run: |
          ls .\choco\tools\test.zip
          ls .\build
