name: Build Choco With GitHub Actions
run-name: "${{ github.actor }} is building the choco packge :)"
on: [push]
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - run: |
          .\test.ps1
